version: '3'
services:
  
  backend-api:
    build: ./backend-api
    container_name: backend-api
    ports:
      - "3001:3000"
    volumes:
      - ./backend-api:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network


  backend-authentication:
    build: ./backend-authentication
    container_name: backend-authentication
    ports:
      - "3002:3000"
    volumes:
      - ./backend-authentication:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network
  
networks:
  my-network:

# volumes:
#   shared-volume:
#     driver: local
#     driver_opts:
#       type: none
#       device: in  
#       o: bind
